apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app
spec:
 replicas: 1
 selector:
   matchLabels:
     app: flask-app
 template:
   metadata:
     labels:
       app: flask-app
   spec:
     containers:
     - name: flask-container
       image: rajeshpeta123/configmapimage:latest
       ports:
       - containerPort: 5000
       env:
       - name: APP_MODE
         valueFrom:
           configMapKeyRef:
             name: app-config
             key: APP_MODE
       - name: LOG_LEVEL
         valueFrom:
           configMapKeyRef:
             name: app-config
             key: LOG_LEVEL
