apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
  namespace: default
spec:
  completions: 5
  parallelism: 2

  template:
   spec:   
      containers:
        - name: parallel-job-container
          image: busybox
          command: ["sh", "-c", "echo Hello from Parallel Job && sleep 5"]
      restartPolicy: Never


