apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: hello
    image: busybox
    command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 30"]
  #restartPolicy: Never
  serviceAccountName: read-pods  # Reference to the ServiceAccount created in serviceaccount