apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-RoleBinding
subjects:
- kind: ServiceAccount
  name: read-pods
  namespace: default
roleRef: 
  kind: Role
  name: read-pods
  apiGroup: rbac.authorization.k8s.io
---