apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}

  initContainers:
  - name: write-message
    image: busybox
    command: ['sh', '-c', 'echo "Hello from Init Container!" > /data/message.txt']
    volumeMounts:
    - name: shared-data
      mountPath: /data

  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
