apiVersion: v1
kind: Pod
metadata:
  name: simple-init-demo
spec:
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'echo "🚀 Init container running..."; sleep 5']

  containers:
  - name: main-app
    image: nginx
    ports:
    - containerPort: 80
