apiVersion: v1
kind: Pod
metadata:
  name: secret-example-pod
  namespace: default
spec:
  containers:
  - name: secret-example-container
    image: busybox
    command: ["sh", "-c", "env; sleep 3600"]
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
  restartPolicy: Always
