apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-logger
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}

  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx

  - name: fluentd
    image: fluent/fluentd
    volumeMounts:
    - name: shared-logs
      mountPath: /fluentd/log
