apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-config
  namespace: dev
data:
  index.html: |
    <html>
      <head>
        <title>Web App Platform</title>
      </head>
      <body>
        <h1>Welcome to the Web App Platform!</h1>
        <p>This is a sample web application running in Kubernetes.</p>
      </body>
    </html>