apiVersion: v1
kind: Pod
metadata:
  name: probe-demo-pod
  namespace: default
spec:
  containers:
    - name: probe-demo-container
      image: nginx
      ports:
        - containerPort: 80


      startupProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 30
        periodSeconds: 5

      livenessProbe:
        httpGet:
          path: /
          port: 80 
        initialDelaySeconds: 5
        periodSeconds: 5

      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
