apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: dev
data:
  index.html: |
    <html>
      <head>
        <title>WebApp - Dev Environment</title>
      </head>
      <body>
        <h1>Welcome to the WebApp - Dev Environment!</h1>
        <p>This is the development environment for our web application.</p>
      </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: prod
data:
  index.html: |
    <html>
      <head>
        <title>WebApp - Production Environment</title>
      </head>
      <body>
        <h1>Welcome to the WebApp - Production Environment!</h1>
        <p>This is the production environment for our web application.</p>
      </body>
    </html>