apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: log-writer
  name: log-writer
spec:
  containers:
  - image: busybox
    name: log-writer
    command: ["sh", "-c", "while true; do echo Hello from $(hostname) >> /logs/pod.log; sleep 5; done"]
    volumeMounts:
    - mountPath: /logs
      name: log-volume
    resources:
      limits:
        memory: "128Mi"
      requests:
        memory: "64Mi"
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: demo-pv-claim