apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-app
spec:
  selector:
    matchLabels:
      app: daemonset-app
  template:
    metadata:
      labels:
        app: daemonset-app
    spec:
      containers:
      - name: daemonset-container
        image: nginx:latest