apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
  namespace: frontend-dev
  labels:
    app: frontend
    tier: web
  annotations:
    maintainer: "rajeshpeta68@gmail.com"
    purpose: "frontend service for multi-tier application"
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  containers:
  - name: frontend-container
    image: nginx:latest
    volumeMounts:
     - name: shared-logs
       mountPath: /usr/share/nginx/html
  - name: sidecar-logger
    image: busybox
    command: ["sh", "-c", "while true; do cat /usr/share/nginx/html/*; sleep 10; done"]
    volumeMounts:
     - name: shared-logs
       mountPath: /usr/share/nginx/html
