apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-volume
  name: app-volume
spec:
  containers:
  - image: busybox
    name: app-volume
    command: ["sh", "-c", "while true; do echo Hello from $(hostname) >> /data/log.txt; sleep 5; done"]
    volumeMounts:
    - mountPath: /data
      name: app-volume
    resources:
      limits:
        memory: "128Mi"
      requests:
        memory: "64Mi"
  volumes:
  - name: app-volume
    emptyDir: {}

