apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx-logger
  name: nginx-logger-pod
spec:
  containers:
   - name: nginx-container
     image: nginx:latest
     ports:
       - containerPort: 80
   - name: log-sidecar
     image: busybox
     command: ["sh", "-c", "while true; do echo 'Logs from sidecar at $(date)' >> /var/log/nginx/access.log; sleep 5; done"]
     volumeMounts:
       - name: shared-logs
         mountPath: /var/log/nginx
  volumes:
     - name: shared-logs
       emptyDir: {}
  restartPolicy: Always
status: {}

  
